---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9   # or the latest
    hooks:
      - id: ruff-check        # linter
        args: [--fix]         # optional: apply autofixes
      - id: ruff-format       # formatter

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: YAML linting
        files: \.ya?ml$
