# Base image: Apache Airflow official image for consistency in ML orchestration
FROM apache/airflow:3.0.3

USER root
COPY --from=ghcr.io/astral-sh/uv:0.5.11 /uv /bin/uv

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
 && rm -rf /var/lib/apt/lists/*

# # Make pip more resilient
# ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
#     PIP_DEFAULT_TIMEOUT=120 \
#     PIP_ONLY_BINARY=":all:"  # prefer wheels

# Install deps with retries + explicit index + timeout
RUN set -eux; \
  for i in 1 2 3 4 5; do \
    python -m pip install --no-cache-dir \
      --retries 5 --timeout 120 -i https://pypi.org/simple \
      mlflow==3.1.4 \
      psycopg2-binary==2.9.10 \
      boto3==1.40.0 \
    && break || { echo "pip attempt $i failed; sleep $((i*5))s"; sleep $((i*5)); }; \
  done

COPY --chown=airflow:root pyproject.toml uv.lock /opt/airflow/

WORKDIR /opt/airflow

# Export locked deps (no dev) -> requirements.txt
RUN uv export --locked --format requirements-txt --no-dev --output-file /tmp/requirements.txt

USER airflow
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# RUN set -eux; \
#   echo "Using constraints: ${AIRFLOW_CONSTRAINTS_URL}"; \
#   for i in 1 2 3 4 5; do \
#     python -m pip install --no-cache-dir --retries 5 --timeout 120 \
#       -r /tmp/requirements.runtime.in \
#       --constraint "${AIRFLOW_CONSTRAINTS_URL}" \
#     && break || { echo "pip attempt $i failed; sleep $((i*5))s"; sleep $((i*5)); }; \
#   done
