# --- STAGE 2: Airflow Runtime built on ML Pipeline ---
# # Base image: uses the ML pipeline image with all code and dependencies pre-installed
# FROM 703501ac4a383650d697544e6bc04f490c9054d894d5a777048ff94dce04099f-ml-pipeline

# # Use Airflow’s default entrypoint script
# ENTRYPOINT ["/entrypoint"]

# # Default command for this container (can be overridden in docker-compose)
# # CMD ["webserver"]

# Airflow runtime built on your pipeline image (which must already include mlflow)
FROM 703501ac4a383650d697544e6bc04f490c9054d894d5a777048ff94dce04099f-ml-pipeline AS runtime

# Inherit the official Airflow entrypoint from the base image; do NOT set CMD here.
# Compose will provide the command per service (api-server/scheduler/triggerer/etc).

WORKDIR /app
ENV PYTHONPATH=/app
